import os
import openai
from PIL import Image
import streamlit as st

openai.api_key = 'insert API KEY'

#chatGPT
def openai_completion(prompt):
    response = openai.Completion.create(
      model="gpt-3.5-turbo",
      #model="text-davinci-003",
      prompt=prompt,
      max_tokens=150,
      temperature=0.5
    )
    return response['choices'][0]['text']

#DALLE
def openai_image(prompt):
    response = openai.Image.create(
      prompt=prompt,
      n=1,
      size="256x256"
    )
    image_url = response['data'][0]['url']
    return image_url


input_text = st.text_area("Please enter text here... 🙋",height=50)
image_button = st.button("Generate Image 🚀")

if image_button and input_text.strip() != "":
    with st.spinner("Loading...💫"):
        image_url = openai_image(input_text)
        st.image(image_url, caption='Generated by OpenAI')
else:
    st.warning("Please enter something! ⚠")